let inputs=0,resets=0,frames=0,dragging=false,px=0,py=0,mode='',time=0,unit=1;
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ler=(a,b,t)=>a+(b-a)*t;
const cols=['#ec765d','#eeb966','#659f9c','#6388ac','#bf7390','#efe3cb'];
function parseHex(c){return [parseInt(c.slice(1,3),16),parseInt(c.slice(3,5),16),parseInt(c.slice(5,7),16)]}
function shade(c,t){let a=parseHex(c);return 'rgb('+a.map(v=>Math.round(clamp(v*t,0,255))).join(',')+')'}
function grad(x,y,r,c1,c2){let g=drawingContext.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c1);g.addColorStop(1,c2);return g}
function bg(c1,c2){let g=drawingContext.createLinearGradient(0,0,1000,760);g.addColorStop(0,c1);g.addColorStop(1,c2);drawingContext.fillStyle=g;drawingContext.fillRect(0,0,1000,760)}
function poly(ps,c){noStroke();fill(c);beginShape();ps.forEach(p=>vertex(p[0],p[1]));endShape(CLOSE)}
function button(id,fn){document.getElementById(id).onclick=()=>{inputs++;artAudio.fx(inputs%7,.7);fn();updateStatus()}}
function choose(id,m){button(id,()=>{mode=m;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.id===id))})}
function setup(){let holder=document.getElementById('stage');let c=createCanvas(holder.clientWidth,holder.clientHeight);c.parent(holder);c.id('art');pixelDensity(Math.min(devicePixelRatio,2));frameRate(30);initialise();initControls();window.addEventListener('resize',()=>{resizeCanvas(holder.clientWidth,holder.clientHeight)});let el=c.elt;el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);dragging=true;let q=position(e);px=q[0];py=q[1];inputs++;onDown(px,py)});el.addEventListener('pointermove',e=>{if(!dragging)return;let q=position(e);inputs++;onDrag(q[0],q[1],q[0]-px,q[1]-py);px=q[0];py=q[1];artAudio.fx(Math.floor(px/80),.45)});el.addEventListener('pointerup',e=>{dragging=false;onUp();updateStatus()});el.addEventListener('pointercancel',()=>dragging=false);button('reset',()=>{resets++;initialise();artAudio.reset()});updateStatus();}
function position(e){let r=document.getElementById('art').getBoundingClientRect();return[(e.clientX-r.left)/r.width*1000,(e.clientY-r.top)/r.height*760]}
function draw(){frames++;time=millis()/1000;push();scale(width/1000,height/760);render();pop()}
function onUp(){}
function updateStatus(){document.getElementById('status').textContent=statusText()}
window.artworkSnapshot=()=>({inputs,resets,frames,state:stateSnapshot(),bounded:bounded(),counts:counts(),audio:artAudio.snapshot()});

let branches=[],rotation=.25,calc=0,calcTo=0,enamel=0,current=1,nextId=0,picked=-1;
const coralPal=[['#e77c70','#eeb599','#ae6991','#8fbdaf'],['#6aadaf','#a6c3a3','#e0bd69','#6893ba'],['#b782b5','#dab3bb','#e9b16f','#759eae']];
function addBranch(parent,a,b,depth){if(branches.length>=210)return;branches.push({id:nextId++,parent,a,b,depth,age:0});return branches[branches.length-1]}
function grow(b,depth){if(depth<=0||branches.length>195)return;let v=b.b.map((n,i)=>n-b.a[i]);for(let s of[-1,1]){let ang=s*(.4+(b.id%4)*.045),len=Math.hypot(...v)*.73;let theta=Math.atan2(v[0],-v[1])+ang,x=b.b[0]+Math.sin(theta)*len,y=b.b[1]-Math.cos(theta)*len,z=b.b[2]+Math.sin(b.id*1.8+s)*len*.52;let nb=addBranch(b.id,b.b,[x,y,z],b.depth+1);if(nb)grow(nb,depth-1)}}
function initialise(){branches=[];nextId=0;for(let i=0;i<3;i++){let a=[(i-1)*75,230,0],b=[(i-1)*95,110-i*8,(i-1)*18];let r=addBranch(-1,a,b,0);grow(r,5)}branches.forEach(b=>b.age=1);rotation=.25;calc=calcTo=0;enamel=0;current=1;mode='rotate';picked=-1;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.id==='rotate'));}
function initControls(){choose('rotate','rotate');choose('prune','prune');choose('graft','graft');button('calcify',()=>calcTo=calcTo?0:1);button('enamel',()=>{enamel=(enamel+1)%3;artAudio.setMood(enamel*6);artAudio.o.tempo=[62,74,68][enamel]});button('current',()=>current=current===1?-1:1)}
function projC(p){let x=p[0]*Math.cos(rotation)+p[2]*Math.sin(rotation),z=p[2]*Math.cos(rotation)-p[0]*Math.sin(rotation);return[500+x,360+p[1]+z*.18,z]}
function pick(x,y){let best=null,dist=80;for(let b of branches){let p=projC(b.b),d=Math.hypot(x-p[0],y-p[1]);if(d<dist){dist=d;best=b}}return best}
function editC(x,y){let b=pick(x,y);if(!b)return;picked=b.id;if(mode==='prune'){let ids=new Set([b.id]);for(let q of branches)if(ids.has(q.parent))ids.add(q.id);branches=branches.filter(q=>!ids.has(q.id));artAudio.fx(1,.8)}if(mode==='graft'){let len=55,base=branches.length;for(let s of[-1,1]){let a=b.b,tip=[a[0]+s*len*.65,a[1]-len,a[2]+s*len*.35];let n=addBranch(b.id,[...a],tip,b.depth+1);if(n&&base<190)grow(n,1)}artAudio.fx(5,.8)}}
function onDown(x,y){if(mode!=='rotate')editC(x,y)}function onDrag(x,y,dx,dy){if(mode==='rotate')rotation+=dx*.01}
function enamelBone(a,c,w,co,id){let dx=c[0]-a[0],dy=c[1]-a[1],len=Math.max(1,Math.hypot(dx,dy)),nx=-dy/len,ny=dx/len,bend=Math.sin(id*1.37)*len*.1;let left=[],right=[];for(let i=0;i<=8;i++){let t=i/8,b=Math.sin(t*Math.PI)*bend,x=ler(a[0],c[0],t)+nx*b,y=ler(a[1],c[1],t)+ny*b,r=w*.5*(1-t*.43);left.push([x+nx*r,y+ny*r]);right.push([x-nx*r,y-ny*r])}poly(left.map(p=>[p[0]+2,p[1]+2]).concat(right.slice().reverse().map(p=>[p[0]+2,p[1]+2])),shade(co,.4));poly(left.concat(right.slice().reverse()),co);noStroke();fill(co);circle(a[0],a[1],w);circle(c[0],c[1],w*.57);stroke(shade(co,1.26));strokeWeight(Math.max(.8,w*.17));strokeCap(ROUND);bezier(a[0]-w*.13,a[1]-w*.09,a[0]+dx*.32+nx*bend*1.2,a[1]+dy*.32+ny*bend*1.2,a[0]+dx*.7+nx*bend,a[1]+dy*.7+ny*bend,c[0]-w*.08,c[1]-w*.08);noStroke();}
function render(){bg('#1f3447','#182833');calc=ler(calc,calcTo,.006);drawingContext.fillStyle=grad(500,360,400,'#5f868649','#17273400');drawingContext.fillRect(0,0,1000,760);noStroke();fill('#0b162a66');ellipse(500,634,550,69);fill('#52646a');rect(293,599,414,24);fill('#718184');ellipse(500,599,414,55);fill('#344752');ellipse(500,623,414,43);for(let b of branches){let par=branches.find(p=>p.id===b.parent);if(!par||par.age>.98)b.age=Math.min(1,b.age+.02)}let sorted=branches.filter(b=>b.age>0).map(b=>{let a=projC(b.a),bp=[...b.b];bp[0]+=Math.sin(time*.5+b.depth)*current*b.depth*1.1;let tip=bp.map((n,i)=>ler(b.a[i],n,b.age));return{b,a,c:projC(tip)}}).sort((a,b)=>a.c[2]-b.c[2]);for(let q of sorted){let {b,a,c}=q,pal=coralPal[enamel],co=pal[Math.min(3,Math.floor(b.depth/2))],w=Math.max(3,20-b.depth*2.4)*(1+calc*.5);enamelBone(a,c,w,co,b.id);if(calc>.12){for(let k=1;k<4;k++){let t=k/4,x=ler(a[0],c[0],t),y=ler(a[1],c[1],t);fill(shade(co,1.12));circle(x+w*.3*Math.sin(k*3),y,w*(.36+calc*.2));fill('#fff4dc99');circle(x-1,y-1,2)}}if(!branches.some(o=>o.parent===b.id)){fill(co);circle(c[0],c[1],7+calc*5);fill('#f5e7c6');circle(c[0]-1.7,c[1]-2,2.5)}}if(picked>=0){let b=branches.find(b=>b.id===picked);if(b){let p=projC(b.b);noFill();stroke('#e3c978');strokeWeight(1);circle(p[0],p[1],28)}}noStroke();fill('#c6d2c7');textFont('Georgia');textSize(12);textAlign(LEFT);text('CORALLIUM / ENAMEL SPECIMEN '+('0'+(enamel+1)),44,55);fill('#91abae');textSize(10);text('an imagined sculpture — not a biological simulation',44,78);fill('#ddc591');textSize(11);text(branches.length+' branching bones / '+Math.round(calc*100)+'% mineral',44,714)}
function statusText(){return({rotate:'拖动旋转转台',prune:'点枝尖剪去后代',graft:'点枝尖嫁接分叉'}[mode])+' · '+['珊瑚珐琅','青铜珐琅','暮紫珐琅'][enamel]+' · '+(calcTo?'正在钙化':'柔枝')}
function stateSnapshot(){return{rotation,calc,calcTo,enamel,current,mode,picked,branches:branches.length}}function bounded(){return branches.length<=210}function counts(){return{branches:branches.length,branchCap:210}}
