/* Original procedural score / Web Audio engine. No sampled music. */
(function(){'use strict';class ArtSound{
constructor(o={}){this.o={tempo:76,scale:[48,52,55,59,62,64,67],seed:1,timbre:'sine',...o};this.muted=false;this.paused=false;this.ctx=null;this.voices=new Set;this.tick=0;this.peak=0;this.errors=0;this.musicNotes=0;this.fxNotes=0;this.lastFx=0;this.next=0;this.timer=null;document.addEventListener('pointerdown',()=>this.unlock(),{capture:true});document.addEventListener('keydown',()=>this.unlock(),{capture:true});window.addEventListener('blur',()=>this.pause());window.addEventListener('pagehide',()=>this.pause());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.pause()});}
async unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=1024;this.wave=new Float32Array(1024);this.master.connect(this.analyser);this.analyser.connect(this.ctx.destination);this.master.gain.value=this.muted?0:.24;}this.paused=false;await this.ctx.resume();if(!this.timer){this.next=this.ctx.currentTime+.02;this.timer=setInterval(()=>this.sequence(),70)}return true;}catch(e){this.errors++;return false}}
sequence(){if(!this.ctx||this.paused||this.muted||this.ctx.state!=='running')return;const t=this.ctx.currentTime;if(t>=this.next){const beat=60/this.o.tempo;const s=this.o.scale,n=this.tick++,ix=(n*3+Math.floor(n/8)+this.o.seed)%s.length;this.note(s[ix]+(n%4===2?12:0),.075,n%4===0?1.15:.58,this.o.timbre,'music');if(n%4===0)this.note(s[(Math.floor(n/4)+this.o.seed)%Math.min(3,s.length)]-12,.065,1.45,'sine','music');this.next=t+beat/2;}}
note(midi,volume=.1,duration=.35,type='sine',kind='fx'){if(!this.ctx||this.paused||this.muted||this.ctx.state!=='running')return;if(this.voices.size>=12){const v=this.voices.values().next().value;this.release(v)}try{const c=this.ctx,t=c.currentTime,osc=c.createOscillator(),gain=c.createGain(),v={osc,gain,done:false};osc.type=['sine','triangle','sawtooth','square'].includes(type)?type:'sine';osc.frequency.setValueAtTime(440*Math.pow(2,(midi-69)/12),t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.018);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(this.master);this.voices.add(v);this.peak=Math.max(this.peak,this.voices.size);osc.onended=()=>this.release(v);osc.start(t);osc.stop(t+duration+.04);kind==='music'?this.musicNotes++:this.fxNotes++;}catch(e){this.errors++}}
release(v){if(!v||v.done)return;v.done=true;try{v.osc.stop()}catch(e){}try{v.osc.disconnect();v.gain.disconnect()}catch(e){}this.voices.delete(v)}
fx(index=0,energy=.7){const now=performance.now();if(now-this.lastFx<65)return;this.lastFx=now;const s=this.o.scale;this.note(s[((Math.floor(index)%s.length)+s.length)%s.length]+12,.08+Math.min(1,Math.max(0,energy))*.08,.16+Math.min(1,energy)*.3,this.o.fxTimbre||'triangle','fx')}
setMood(n){this.o.seed=(Math.abs(Math.floor(n))+1)%31;}
toggle(){this.muted=!this.muted;if(this.master)this.master.gain.setValueAtTime(this.muted?0:.24,this.ctx.currentTime);if(this.muted){for(const v of [...this.voices])this.release(v)}this.refresh();return this.muted;}
refresh(){const el=document.querySelector('#mute');if(el){el.textContent=this.muted?'声音 · 关':'声音 · 开';el.setAttribute('aria-pressed',String(this.muted));}}
bind(){const b=document.querySelector('#mute');if(b)b.addEventListener('click',()=>this.toggle());this.refresh();return this;}
reset(){this.tick=0;for(const v of [...this.voices])this.release(v);if(this.ctx)this.next=this.ctx.currentTime+.04;this.refresh();}
pause(){this.paused=true;if(this.timer){clearInterval(this.timer);this.timer=null}if(this.master)this.master.gain.setValueAtTime(0,this.ctx.currentTime);for(const v of [...this.voices])this.release(v);if(this.ctx&&this.ctx.state==='running')this.ctx.suspend().catch(()=>this.errors++);}
snapshot(){let rms=0;if(this.analyser&&this.ctx.state==='running'){this.analyser.getFloatTimeDomainData(this.wave);let s=0;for(let i=0;i<this.wave.length;i++)s+=this.wave[i]*this.wave[i];rms=Math.sqrt(s/this.wave.length)}return{state:this.ctx?this.ctx.state:'not-created',unlocked:!!this.ctx,muted:this.muted,paused:this.paused,voices:this.voices.size,peakVoices:this.peak,nodeCount:this.ctx?2+this.voices.size*2:0,nodeLimit:26,rms,errors:this.errors,musicNotes:this.musicNotes,fxNotes:this.fxNotes}}}
const originalUnlock=ArtSound.prototype.unlock;ArtSound.prototype.unlock=async function(){const result=await originalUnlock.call(this);if(this.master)this.master.gain.setValueAtTime(this.muted?0:.24,this.ctx.currentTime);return result};window.ArtSound=ArtSound;})();
