const ID=6;let chips=[],cuts=[],flowers=[],bubbles=[],layer=0,soapHue=0;const pal=['#da8174','#9eb7a0','#e8bd65','#8a90b1','#c9a5b8'];
function reset(){chips=Array.from({length:38},()=>({x:R(.19,.78),y:R(.19,.75),s:R(.012,.035),a:R(0,6),c:pal[Math.floor(R(0,5))]}));cuts=[];flowers=[];bubbles=[];layer=0;soapHue=0}
function action(i){status(['拖一条切口，揭开新的层纹','点按把碎皂镶入表面','点按压下五瓣花章','拖动打出细密泡沫','拖动擦开泡沫，露出你的皂石'][i]);if(i===0&&cuts.length>9){cuts=[];layer++}sound.setMood(i+layer)}
function down(p){if(mode===0){cuts.push({x:p.x,y:p.y,x2:p.x,y2:p.y});if(cuts.length>12)cuts.shift();layer++}if(mode===1){chips.push({x:p.x,y:p.y,s:R(.015,.036),a:R(0,6),c:pal[(chips.length+layer)%5]});if(chips.length>130)chips.shift()}if(mode===2){flowers.push({...p,a:R(0,6)});if(flowers.length>30)flowers.shift()}if(mode===3)foam(p);if(mode===4)wash(p)}
function foam(p){for(let i=0;i<6;i++)bubbles.push({x:p.x+R(-.035,.035),y:p.y+R(-.03,.03),r:R(.009,.033),life:1});bubbles=bubbles.slice(-200)}function wash(p){bubbles.forEach(b=>{if(Math.hypot(b.x-p.x,b.y-p.y)<.11)b.life-=.35});bubbles=bubbles.filter(b=>b.life>0)}
function move(p,last){if(mode===0){let c=cuts[cuts.length-1];c.x2=p.x;c.y2=p.y}if(mode===1&&frame%4===0)down(p);if(mode===3)foam(p);if(mode===4)wash(p);if(frame%10===0)fx('move',mode+layer)}function up(){}
function draw(t){bg('#e7e2d5');grad(W*.8,H*.16,W*.5,'#fffde4bb');line(W*.05,H*.83,W*.95,H*.83,'#c5bdac');text('LAYER / '+String(layer+1).padStart(2,'0'),W*.08,H*.11,12);text('HANDCRAFTED · SLOW STUDIO',W*.08,H*.91,10);g.save();g.translate(W*.5,H*.45);g.rotate(-.1);shadow(30);round(-W*.31,-H*.29,W*.62,H*.60,Math.min(W,H)*.05,'#bbb7a5');g.restore();
g.save();g.translate(W*.5,H*.45);g.rotate(-.1);round(-W*.31,-H*.31,W*.62,H*.58,Math.min(W,H)*.045,'#f4e8d2');g.clip();let lg=g.createLinearGradient(0,-H*.3,0,H*.3);lg.addColorStop(0,'#fff6df');lg.addColorStop(.55,layer%2?'#edd9d2':'#eadcc3');lg.addColorStop(1,'#dbceb4');g.fillStyle=lg;g.fillRect(-W*.4,-H*.4,W*.8,H*.8);for(let i=0;i<8;i++){g.beginPath();for(let j=0;j<60;j++){let x=-W*.35+j/59*W*.7,y=-H*.28+i*H*.08+Math.sin(j*.1+i+layer*.4)*H*.025;j?g.lineTo(x,y):g.moveTo(x,y)}g.strokeStyle=rgba(pal[(i+layer)%5],.12);g.lineWidth=H*.03;g.stroke()}
chips.forEach(c=>{g.save();g.translate((c.x-.5)*W,(c.y-.45)*H);g.rotate(c.a);g.beginPath();g.moveTo(-c.s*W,-c.s*H*.7);g.lineTo(c.s*W*.75,-c.s*H);g.lineTo(c.s*W,c.s*H*.45);g.lineTo(-c.s*W*.5,c.s*H);g.closePath();g.fillStyle=c.c;g.fill();line(-c.s*W,-c.s*H*.7,c.s*W*.75,-c.s*H,'#ffffff70',2);g.restore()});
flowers.forEach(f=>{g.save();g.translate((f.x-.5)*W,(f.y-.45)*H);g.rotate(f.a);for(let k=0;k<5;k++){g.rotate(Math.PI*2/5);g.beginPath();g.ellipse(0,-H*.025,W*.015,H*.032,0,0,7);g.strokeStyle='#a4877455';g.lineWidth=2;g.stroke();}circle(0,0,3,'#aa8c7866');g.restore()});cuts.forEach(c=>{line((c.x-.5)*W,(c.y-.45)*H,(c.x2-.5)*W,(c.y2-.45)*H,'#bda68b',3);line((c.x-.5)*W,(c.y-.45)*H+3,(c.x2-.5)*W,(c.y2-.45)*H+3,'#fff9e7',2)});bubbles.forEach(b=>{circle((b.x-.5)*W,(b.y-.45)*H,b.r*W,'#ffffffb0');g.strokeStyle='#eee9edcc';g.stroke();circle((b.x-.5)*W-b.r*W*.3,(b.y-.45)*H-b.r*W*.4,b.r*W*.17,'#fff')});g.restore();
g.save();shadow(10);round(W*.70,H*.70,W*.15,H*.12,15,'#e6ab97');g.restore();text('SOAP',W*.775,H*.77,12,'#9b6152','center');grain(layer)}
function snapshot(){return {layer,cuts:cuts.length,flowers:flowers.length,foam:bubbles.length,mode}}function counts(){return {chips:chips.length,cuts:cuts.length,flowers:flowers.length,bubbles:bubbles.length}}
