const{chromium}=require('/Users/tao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve('batch07-work'),out=path.resolve('batch07-evidence');fs.mkdirSync(out,{recursive:true});const slugs=fs.readdirSync(root).filter(s=>fs.existsSync(path.join(root,s,'metadata.json'))).sort();const selected=process.env.QA_SLUGS?slugs.filter(s=>process.env.QA_SLUGS.split(',').includes(s)):slugs;const snapshot=p=>p.evaluate(()=>JSON.parse(document.querySelector('#qa').textContent));
async function run(slug,mobile){const b=await chromium.launch({headless:true,chromiumSandbox:true,args:['--mute-audio']}),v=mobile?{width:390,height:844}:{width:1440,height:900},c=await b.newContext({viewport:v,isMobile:mobile,hasTouch:mobile}),p=await c.newPage(),cdp=await c.newCDPSession(p),r={slug,device:mobile?'mobile':'desktop',errors:[],consoleErrors:[],requests:[],physicalPhone:false,humanListening:false,stages:[]};p.on('pageerror',e=>r.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')r.consoleErrors.push(m.text())});p.on('request',x=>r.requests.push(x.url()));
try{await p.addInitScript(()=>{const N=AudioContext;window.__audioNodes=new Set();window.AudioContext=class extends N{constructor(...args){super(...args);window.__audioContext=this;}createGain(){const n=super.createGain();return n;}createOscillator(){const n=super.createOscillator();window.__audioNodes.add(n);n.addEventListener('ended',()=>window.__audioNodes.delete(n));return n;}}});const response=await p.goto('http://127.0.0.1:8307/'+slug+'/?qa');r.htmlSHA=crypto.createHash('sha256').update(await response.body()).digest('hex');await p.waitForTimeout(350);r.initial=await snapshot(p);await p.screenshot({path:path.join(out,slug+'-'+r.device+'-initial.png')});const meta=JSON.parse(fs.readFileSync(path.join(root,slug,'metadata.json'))),start=Date.now();
async function click(selector){if(mobile)await p.locator(selector).tap();else await p.locator(selector).click();}
async function point(xy){const box=await p.locator('canvas').boundingBox();let [x,y]=xy;if(meta.canonicalArtboard){const [aw,ah]=meta.canonicalArtboard,s=Math.min(box.width/aw,box.height/ah);return{x:box.x+(box.width-aw*s)/2+x*aw*s,y:box.y+(box.height-ah*s)/2+y*ah*s};}return{x:box.x+x*box.width,y:box.y+y*box.height};}
async function gesture(from,to){const a=await point(from),z=await point(to||from);if(mobile)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1}]});else{await p.mouse.move(a.x,a.y);await p.mouse.down();}for(let i=1;i<=8;i++){const q={x:a.x+(z.x-a.x)*i/8,y:a.y+(z.y-a.y)*i/8};if(mobile)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...q,id:1}]});else await p.mouse.move(q.x,q.y);await p.waitForTimeout(30);}if(mobile)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else await p.mouse.up();await p.waitForTimeout(120);}
async function step(t){const ids=t.actions||[t.control||t.action];for(const id of ids)await click('[data-tool="'+id+'"]');for(const xy of t.clicks||[])await gesture(xy,xy);if(t.from)await gesture(t.from,t.to);if(t.target){const s=await snapshot(p);let xy=t.target.startsWith('holes')?[s.art.holes[0].x/1000,s.art.holes[0].y/700]:[.52,.69];for(let i=0;i<(t.clickCount||1);i++)await gesture(xy,t.deltaPixels?[xy[0]+t.deltaPixels[0]/1000,xy[1]+t.deltaPixels[1]/700]:xy);}if(t.advanceSeconds)await p.waitForTimeout(Math.min(t.advanceSeconds*1000,12000));await p.waitForTimeout(150);r.stages.push({step:t,qa:await snapshot(p)});}
for(const t of meta.testPlan)await step(t);await p.screenshot({path:path.join(out,slug+'-'+r.device+'-composed.png')});r.composed=await snapshot(p);for(let repeat=0;repeat<100;repeat++){const t=meta.testPlan[repeat%meta.testPlan.length];const id=t.control||t.action||t.actions?.[0];await click('[data-tool="'+id+'"]');}r.stress=await snapshot(p);
for(let round=0;round<3;round++){await click('#sound');await p.waitForTimeout(300);await gesture([.5,.4],[.56,.5]);r.stages.push({muteRound:round,qa:await snapshot(p)});await click('#reset');await p.waitForTimeout(220);r.stages.push({resetRound:round,qa:await snapshot(p)});await click('#sound');await gesture([.5,.4],[.6,.45]);}
const artBefore=await p.evaluate(()=>ART.stats());await p.setViewportSize({width:v.width+30,height:v.height+25});await p.waitForTimeout(250);r.resizePreserved=JSON.stringify(artBefore)===JSON.stringify(await p.evaluate(()=>ART.stats()));await p.setViewportSize(v);
// Native iframe focus produces a trusted top-window blur.
await p.evaluate(()=>{window.__blurs=[];window.addEventListener('blur',e=>__blurs.push(e.isTrusted));const f=document.createElement('iframe');f.id='native-focus';f.srcdoc='<button id=b style="width:120px;height:60px">Focus</button>';f.style='position:fixed;left:5px;top:5px;width:150px;height:80px;z-index:99999';document.body.append(f)});const fb=p.frameLocator('#native-focus').locator('#b');if(mobile)await fb.tap();else await fb.click();await p.waitForTimeout(350);r.blur=await snapshot(p);r.blurTrusted=await p.evaluate(()=>__blurs.some(Boolean));r.nodesAfterBlur=r.blur.audio.activeVoices;r.connectedAfterBlur=r.blur.audio.connectedNodes;await p.locator('#native-focus').evaluate(e=>e.remove());await gesture([.4,.4],[.6,.5]);
let cycle=0;while(Date.now()-start<65000){const t=meta.testPlan[cycle++%meta.testPlan.length];await step({...t,advanceSeconds:undefined});await gesture([.3,.45],[.65,.55]);await p.waitForTimeout(150)}r.durationSeconds=(Date.now()-start)/1000;r.final=await snapshot(p);await p.screenshot({path:path.join(out,slug+'-'+r.device+'-final.png')});r.buttons=await p.locator('button').evaluateAll(bs=>bs.filter(x=>x.getBoundingClientRect().height>0).map(x=>({text:x.textContent,height:x.getBoundingClientRect().height,right:x.getBoundingClientRect().right,bottom:x.getBoundingClientRect().bottom})));r.heap=await cdp.send('Runtime.getHeapUsage');
await p.evaluate(()=>{addEventListener('pagehide',e=>sessionStorage.setItem('pagehideQA',JSON.stringify({trusted:e.isTrusted,nodes:__audioNodes.size,state:__audioContext.state,qa:JSON.parse(document.querySelector('#qa').textContent)})));const a=document.createElement('a');a.id='native-leave';a.href='/';a.textContent='Leave';a.style='position:fixed;top:5px;left:5px;padding:20px;background:white;z-index:99999';document.body.append(a)});await click('#native-leave');await p.waitForURL('http://127.0.0.1:8307/');r.pagehide=await p.evaluate(()=>JSON.parse(sessionStorage.getItem('pagehideQA')));const muted=r.stages.filter(x=>x.muteRound!==undefined||x.resetRound!==undefined);r.assertions={initialLocked:r.initial.audioState==='locked',realInputs:r.final.trusted>100,musicNonzero:r.final.audio.musicPeak>1e-6,fxNonzero:r.final.audio.fxPeak>1e-6,outputNonzero:r.final.audio.outPeak>1e-6,muteZero:muted.every(x=>x.qa.audio.out===0),resetPreservesMute:muted.filter(x=>x.resetRound!==undefined).every(x=>x.qa.muted),blurTrusted:r.blurTrusted,blurSuspended:r.blur.audioState==='suspended',blurReclaims:r.nodesAfterBlur===0&&r.connectedAfterBlur===6,pagehideTrusted:r.pagehide.trusted,resizePreserved:r.resizePreserved,voiceLimit:r.final.audio.maxVoices<=18,duration:r.durationSeconds>=60&&r.durationSeconds<=90,noErrors:!r.errors.length&&!r.consoleErrors.length&&!r.final.errors.length,buttonTargets:r.buttons.every(x=>x.height>=43&&x.right<=v.width+1&&x.bottom<=v.height+1),noExternal:r.requests.every(x=>x.startsWith('http://127.0.0.1:8307/')),fps:r.final.fps>=20,heapBound:r.heap.usedSize<180000000};r.pass=Object.values(r.assertions).every(Boolean);
}catch(e){r.failure=e.stack;r.pass=false}finally{await b.close();fs.writeFileSync(path.join(out,slug+'-'+r.device+'.json'),JSON.stringify(r,null,2));console.log(JSON.stringify({slug,device:r.device,pass:r.pass,assertions:r.assertions,failure:r.failure}));}}
(async()=>{let i=0;const cases=selected.flatMap(s=>[{s,m:true},{s,m:false}]);await Promise.all(Array.from({length:Number(process.env.QA_WORKERS||4)},async()=>{while(i<cases.length){const a=cases[i++];await run(a.s,a.m)}}))})();
