(()=>{'use strict';
const ART=window.ART,canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d',{alpha:false});
const q=new URLSearchParams(location.search),qa=q.has('qa');
const $=s=>document.querySelector(s);let w=0,h=0,dpr=1,last=0,elapsed=0,frames=0,sumdt=0,maxdt=0,active=false,px=0,py=0,down=false,tool=ART.tools[0]?.id,muted=false;
const metrics={trusted:0,downs:0,moves:0,actions:0,resets:0,resizes:0,errors:[],start:Date.now(),audio:{musicPeak:0,fxPeak:0,outPeak:0}};
window.addEventListener('error',e=>metrics.errors.push(e.message));window.addEventListener('unhandledrejection',e=>metrics.errors.push(String(e.reason)));
for(const[k,v]of Object.entries(ART.palette))document.body.style.setProperty('--'+k,v);document.title=ART.title+' · Little Worlds';$('#title').textContent=ART.title;$('#hint').textContent=ART.subtitle;
const sounds={ctx:null,music:null,fxbus:null,master:null,ma:null,fa:null,oa:null,timer:null,unlocked:false,suspended:true,beat:0,voices:new Set(),maxVoices:0,musicCount:0,fxCount:0};
const piece=Number(document.body.dataset.number||1)-1;const scales=[[0,2,5,7,9,12,14,17],[0,3,5,7,10,12,15,17],[0,2,4,7,9,12,14,16],[0,2,5,7,11,12,14,17],[0,3,5,7,10,12,15,17],[0,2,4,7,9,12,14,16],[0,2,4,5,7,9,12,14],[0,2,5,7,9,12,14,17],[0,3,5,6,7,10,12,15],[0,2,5,7,9,12,14,17]], motifs=[[0,4,2,6,1,3,5,2,0,5,3,7,4,2,1,6],[0,0,3,2,4,3,1,2,5,4,1,3,2,6,2,0],[0,3,6,2,5,1,7,3,4,2,6,1,5,3,2,0],[0,4,7,4,1,5,6,3,2,6,4,2,1,3,5,0],[0,2,1,4,2,5,3,6,4,7,3,5,2,4,1,0],[0,2,4,3,1,3,5,4,2,4,6,5,3,5,7,0],[0,2,4,2,0,3,5,3,1,4,6,4,2,5,7,4],[4,2,0,2,5,3,1,3,6,4,2,4,7,5,3,0],[0,3,2,5,1,4,3,6,2,5,4,7,3,6,5,0],[0,4,2,1,5,3,2,6,4,3,7,5,2,4,1,0]],scale=scales[piece%10],root=45+(piece+1)%8,motif=motifs[piece%10],tempo=[620,480,520,680,390,550,330,360,300,710][piece%10];
function measure(a){if(!a)return 0;const arr=new Float32Array(256);a.getFloatTimeDomainData(arr);let n=0;for(const x of arr)n+=x*x;return Math.sqrt(n/arr.length);}
function note(midi,duration,gain,bus,kind=0){if(!sounds.ctx||sounds.ctx.state!=='running'||muted||sounds.suspended||sounds.voices.size>=18)return;const ac=sounds.ctx,osc=ac.createOscillator(),amp=ac.createGain(),t=ac.currentTime;osc.type=kind===2?'sine':kind===1?'triangle':'sine';osc.frequency.setValueAtTime(440*Math.pow(2,(midi-69)/12),t);if(kind===3)osc.frequency.exponentialRampToValueAtTime(80,t+duration);amp.gain.setValueAtTime(0,t);amp.gain.linearRampToValueAtTime(gain,t+.012);amp.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(amp);amp.connect(bus);const v={osc,amp};sounds.voices.add(v);sounds.maxVoices=Math.max(sounds.maxVoices,sounds.voices.size);osc.onended=()=>{osc.disconnect();amp.disconnect();sounds.voices.delete(v)};osc.start(t);osc.stop(t+duration+.03);}
function tick(){if(muted||sounds.suspended||document.hidden)return;const i=sounds.beat++;note(root+12+scale[motif[i%16]],.9,.055,sounds.music,i%3===0?1:0);if(i%4===0)note(root-12+scale[(i/4|0)%4],1.55,.035,sounds.music,2);if(i%8===6)note(root+24+scale[3],.45,.022,sounds.music);sounds.musicCount++;}
function halt(){sounds.suspended=true;clearInterval(sounds.timer);sounds.timer=null;if(sounds.master){sounds.master.gain.cancelScheduledValues(sounds.ctx.currentTime);sounds.master.gain.setValueAtTime(0,sounds.ctx.currentTime);}for(const v of [...sounds.voices]){try{v.osc.stop();}catch{}v.osc.disconnect();v.amp.disconnect();sounds.voices.delete(v);}if(sounds.ctx&&sounds.ctx.state==='running')sounds.ctx.suspend().catch(()=>{});}
async function unlock(e){if(e&&!e.isTrusted)return;if(!sounds.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;sounds.ctx=new C();const ac=sounds.ctx;sounds.music=ac.createGain();sounds.fxbus=ac.createGain();sounds.master=ac.createGain();sounds.ma=ac.createAnalyser();sounds.fa=ac.createAnalyser();sounds.oa=ac.createAnalyser();for(const a of[sounds.ma,sounds.fa,sounds.oa])a.fftSize=256;sounds.music.connect(sounds.ma);sounds.ma.connect(sounds.master);sounds.fxbus.connect(sounds.fa);sounds.fa.connect(sounds.master);sounds.master.connect(sounds.oa);sounds.oa.connect(ac.destination);}
try{await sounds.ctx.resume();sounds.unlocked=true;sounds.suspended=false;sounds.master.gain.setValueAtTime(muted?0:.68,sounds.ctx.currentTime);if(!muted&&!sounds.timer){tick();sounds.timer=setInterval(tick,tempo);}}catch{}
}
window.SOUND={fx(midi=64,kind=0){if(!sounds.unlocked||muted||sounds.suspended)return;midi=Math.max(24,Math.min(100,Number(midi)||64));kind=Math.max(0,Math.min(3,Number(kind)||0));note(midi,.17+kind*.035,.08,sounds.fxbus,kind%4);sounds.fxCount++;}};
function audioLabel(){$('#sound').textContent=muted?'声音已关':'声音开启';$('#sound').setAttribute('aria-pressed',String(muted));$('#soundnote').textContent=sounds.unlocked?(muted?'已静音，重置会保留':'音乐与操作音效已开启'):'轻触画面，开启声音';}
for(const a of ART.tools){const b=document.createElement('button');b.textContent=a.label;b.dataset.tool=a.id;b.type='button';b.setAttribute('aria-pressed',String(a.id===tool));b.addEventListener('click',e=>{metrics.trusted+=e.isTrusted?1:0;metrics.actions++;tool=a.id;for(const x of document.querySelectorAll('[data-tool]'))x.setAttribute('aria-pressed',String(x.dataset.tool===tool));unlock(e);ART.action(a.id);audioLabel();});$('#tools').append(b);}
$('#sound').addEventListener('click',async e=>{metrics.trusted+=e.isTrusted?1:0;muted=!muted;if(muted){if(sounds.master)sounds.master.gain.setValueAtTime(0,sounds.ctx.currentTime);halt();}else await unlock(e);audioLabel();});
$('#reset').addEventListener('click',e=>{metrics.trusted+=e.isTrusted?1:0;metrics.resets++;down=false;halt();sounds.beat=0;ART.init();tool=ART.tools[0]?.id;for(const x of document.querySelectorAll('[data-tool]'))x.setAttribute('aria-pressed',String(x.dataset.tool===tool));if(!muted)unlock(e);audioLabel();});
$('#capture').addEventListener('click',()=>{const a=document.createElement('a');a.download=ART.title+'-画面.png';a.href=canvas.toDataURL('image/png');a.click();});
function point(e){const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);const[x,y]=point(e);down=true;px=x;py=y;metrics.downs++;metrics.trusted+=e.isTrusted?1:0;unlock(e).then(()=>{audioLabel();window.SOUND.fx(root+24,1);});ART.pointer('down',x,y,0,0);});
canvas.addEventListener('pointermove',e=>{if(!down)return;e.preventDefault();const[x,y]=point(e);metrics.moves++;metrics.trusted+=e.isTrusted?1:0;ART.pointer('move',x,y,x-px,y-py);px=x;py=y;});
function up(e){if(!down)return;const[x,y]=point(e);down=false;ART.pointer('up',x,y,x-px,y-py);}
canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('lostpointercapture',()=>down=false);
window.addEventListener('blur',()=>{halt();down=false;});window.addEventListener('pagehide',halt);document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden)halt();});window.addEventListener('focus',()=>{last=0;});
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);metrics.resizes++;}new ResizeObserver(resize).observe(canvas);resize();ART.init();audioLabel();
let report=0;function frame(now){requestAnimationFrame(frame);let rawdt=last?(now-last)/1000:.016;let dt=Math.min(.08,rawdt);last=now;if(document.hidden)return;elapsed+=dt;frames++;sumdt+=rawdt;maxdt=Math.max(maxdt,rawdt);ctx.save();try{ART.draw(ctx,w,h,elapsed,dt);}catch(e){if(!metrics.errors.includes(e.message)){metrics.errors.push(e.message);console.error(e)}}finally{ctx.restore();}if(now-report>100){report=now;const music=measure(sounds.ma),fx=measure(sounds.fa),out=measure(sounds.oa);metrics.audio.musicPeak=Math.max(metrics.audio.musicPeak,music);metrics.audio.fxPeak=Math.max(metrics.audio.fxPeak,fx);metrics.audio.outPeak=Math.max(metrics.audio.outPeak,out);const dat={title:ART.title,elapsed:+elapsed.toFixed(1),wallSeconds:+((Date.now()-metrics.start)/1000).toFixed(1),trusted:metrics.trusted,downs:metrics.downs,moves:metrics.moves,actions:metrics.actions,resets:metrics.resets,resizes:metrics.resizes,viewport:[w,h],fps:Math.round(frames/sumdt),maxFrameMs:Math.round(maxdt*1000),muted,audioState:sounds.ctx?.state||'locked',audio:{music,fx,out,...metrics.audio,musicCount:sounds.musicCount,fxCount:sounds.fxCount,activeVoices:sounds.voices.size,connectedNodes:sounds.ctx?6+sounds.voices.size*2:0,suspended:sounds.suspended,maxVoices:sounds.maxVoices,limit:18},art:ART.stats(),errors:metrics.errors};$('#qa').textContent=JSON.stringify(dat);}}
if(qa)document.body.classList.add('qa');requestAnimationFrame(frame);
})();
