let inputs=0,resets=0,frames=0,dragging=false,px=0,py=0,mode='',time=0,unit=1;
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ler=(a,b,t)=>a+(b-a)*t;
const cols=['#ec765d','#eeb966','#659f9c','#6388ac','#bf7390','#efe3cb'];
function parseHex(c){return [parseInt(c.slice(1,3),16),parseInt(c.slice(3,5),16),parseInt(c.slice(5,7),16)]}
function shade(c,t){let a=parseHex(c);return 'rgb('+a.map(v=>Math.round(clamp(v*t,0,255))).join(',')+')'}
function grad(x,y,r,c1,c2){let g=drawingContext.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c1);g.addColorStop(1,c2);return g}
function bg(c1,c2){let g=drawingContext.createLinearGradient(0,0,1000,760);g.addColorStop(0,c1);g.addColorStop(1,c2);drawingContext.fillStyle=g;drawingContext.fillRect(0,0,1000,760)}
function poly(ps,c){noStroke();fill(c);beginShape();ps.forEach(p=>vertex(p[0],p[1]));endShape(CLOSE)}
function button(id,fn){document.getElementById(id).onclick=()=>{inputs++;artAudio.fx(inputs%7,.7);fn();updateStatus()}}
function choose(id,m){button(id,()=>{mode=m;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.id===id))})}
function setup(){let holder=document.getElementById('stage');let c=createCanvas(holder.clientWidth,holder.clientHeight);c.parent(holder);c.id('art');pixelDensity(Math.min(devicePixelRatio,2));frameRate(30);initialise();initControls();window.addEventListener('resize',()=>{resizeCanvas(holder.clientWidth,holder.clientHeight)});let el=c.elt;el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);dragging=true;let q=position(e);px=q[0];py=q[1];inputs++;onDown(px,py)});el.addEventListener('pointermove',e=>{if(!dragging)return;let q=position(e);inputs++;onDrag(q[0],q[1],q[0]-px,q[1]-py);px=q[0];py=q[1];artAudio.fx(Math.floor(px/80),.45)});el.addEventListener('pointerup',e=>{dragging=false;onUp();updateStatus()});el.addEventListener('pointercancel',()=>dragging=false);button('reset',()=>{resets++;initialise();artAudio.reset()});updateStatus();}
function position(e){let r=document.getElementById('art').getBoundingClientRect();return[(e.clientX-r.left)/r.width*1000,(e.clientY-r.top)/r.height*760]}
function draw(){frames++;time=millis()/1000;push();scale(width/1000,height/760);render();pop()}
function onUp(){}
function updateStatus(){document.getElementById('status').textContent=statusText()}
window.artworkSnapshot=()=>({inputs,resets,frames,state:stateSnapshot(),bounded:bounded(),counts:counts(),audio:artAudio.snapshot()});

let dots=[],form=0,spread=0,spreadTo=0,angle=.25,tilt=.1,colourPhase=0,repair=false;
function initialise(){repair=false;colourPhase=0;form=0;spread=spreadTo=0;angle=.25;tilt=.1;mode='press';dots=[];for(let i=0;i<3200;i++){let u=(i*.61803398875)%1,v=(i*.754877666)%1;dots.push({u,v,dx:0,dy:0,dz:0,group:i%3})}document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.id==='press'));}
function initControls(){choose('press','press');choose('gather','gather');choose('orbit','orbit');button('layers',()=>spreadTo=spreadTo?0:1);button('restore',()=>{repair=true;spreadTo=0});button('form',()=>{form=(form+1)%3;colourPhase++;artAudio.setMood(form*5);artAudio.o.tempo=[66,82,74][form]})}
function base(d){let a=d.u*TAU,v=d.v;if(form===0){let r=105+190*v;return[(r*Math.cos(a))*(.45+.6*v),r*Math.sin(a)*.86,Math.sin(a*3+v*8)*45+80*Math.cos(v*Math.PI)]}if(form===1){let r=90+180*v;return[r*Math.cos(a),r*Math.sin(a)*.9,80*Math.sin(a*2+v*5)]}let r=180*Math.sin(v*Math.PI);return[r*Math.cos(a)*(1+.25*Math.cos(a*5)),(v-.5)*550,r*Math.sin(a)*.55]}
function project(d){let b=base(d),x=b[0]+d.dx,y=b[1]+d.dy+(d.group-1)*spread*115,z=b[2]+d.dz+(d.group-1)*spread*85;let xx=x*Math.cos(angle)+z*Math.sin(angle),zz=z*Math.cos(angle)-x*Math.sin(angle),yy=y*Math.cos(tilt)-zz*Math.sin(tilt);return[500+xx,380+yy,zz]}
function deform(x,y){if(mode==='orbit')return;repair=false;for(let d of dots){let p=project(d),rx=p[0]-x,ry=p[1]-y,dist=Math.hypot(rx,ry),w=Math.max(0,1-dist/160);if(!w)continue;if(mode==='press'){d.dx=clamp(d.dx+rx*w*.06,-150,150);d.dy=clamp(d.dy+ry*w*.06,-150,150);d.dz=clamp(d.dz+35*w,-230,230)}else{d.dx=clamp(d.dx-rx*w*.065,-150,150);d.dy=clamp(d.dy-ry*w*.065,-150,150);d.dz=clamp(d.dz-16*w,-230,230)}}artAudio.fx(Math.floor(y/100),.7)}
function onDown(x,y){deform(x,y)}function onDrag(x,y,dx,dy){if(mode==='orbit'){angle+=dx*.009;tilt=clamp(tilt+dy*.004,-.8,.8)}else deform(x,y)}
function render(){if(repair)for(let d of dots){d.dx*=.955;d.dy*=.955;d.dz*=.955}bg('#112435','#283143');spread=ler(spread,spreadTo,.025);drawingContext.fillStyle=grad(500,380,370,'#294e5777','#15222f00');drawingContext.fillRect(0,0,1000,760);noFill();stroke('#8eada324');strokeWeight(1);ellipse(500,625,610,68);ellipse(500,625,500,42);noStroke();fill('#08131c4a');ellipse(500,624,490,40);let ps=[];for(let d of dots){let p=project(d);p[1]+=Math.sin(time*.7+d.u*TAU)*3;ps.push({d,p})}ps.sort((a,b)=>a.p[2]-b.p[2]);for(let {d,p} of ps){let c=cols[(d.group+Math.floor(d.v*3)+colourPhase)%6],sz=2.4+(p[2]+250)/135;fill(shade(c,.72+(p[2]+250)/800));circle(p[0],p[1],sz);if(d.u<.11){fill('#fff2d477');circle(p[0]-sz*.17,p[1]-sz*.17,sz*.32)}}fill('#d1b482');textFont('Georgia');textSize(12);textAlign(LEFT);text('CHROMATIC CHOIR  /  STUDY '+('0'+(form+1)),44,56);textSize(10);fill('#b4c5c3');text('3200 pigment voices',44,78);if(dragging){noFill();stroke('#dfc98b88');ellipse(px,py,95,95)}}
function statusText(){return['贝壳曲面','盘涡曲面','冠叶曲面'][form]+' · '+(spreadTo?'三层展开':'合奏')+' · '+({press:'按压色点',gather:'聚拢色点',orbit:'旋转观赏'}[mode])}
function stateSnapshot(){return{form,spread,angle,tilt,mode,deformed:dots.filter(d=>Math.abs(d.dx)+Math.abs(d.dy)+Math.abs(d.dz)>5).length}}function bounded(){return dots.length===3200}function counts(){return{dots:dots.length,cap:3200}}
