let inputs=0,resets=0,frames=0,dragging=false,px=0,py=0,mode='',time=0,unit=1;
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ler=(a,b,t)=>a+(b-a)*t;
const cols=['#ec765d','#eeb966','#659f9c','#6388ac','#bf7390','#efe3cb'];
function parseHex(c){return [parseInt(c.slice(1,3),16),parseInt(c.slice(3,5),16),parseInt(c.slice(5,7),16)]}
function shade(c,t){let a=parseHex(c);return 'rgb('+a.map(v=>Math.round(clamp(v*t,0,255))).join(',')+')'}
function grad(x,y,r,c1,c2){let g=drawingContext.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c1);g.addColorStop(1,c2);return g}
function bg(c1,c2){let g=drawingContext.createLinearGradient(0,0,1000,760);g.addColorStop(0,c1);g.addColorStop(1,c2);drawingContext.fillStyle=g;drawingContext.fillRect(0,0,1000,760)}
function poly(ps,c){noStroke();fill(c);beginShape();ps.forEach(p=>vertex(p[0],p[1]));endShape(CLOSE)}
function button(id,fn){document.getElementById(id).onclick=()=>{inputs++;artAudio.fx(inputs%7,.7);fn();updateStatus()}}
function choose(id,m){button(id,()=>{mode=m;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.id===id))})}
function setup(){let holder=document.getElementById('stage');let c=createCanvas(holder.clientWidth,holder.clientHeight);c.parent(holder);c.id('art');pixelDensity(Math.min(devicePixelRatio,2));frameRate(30);initialise();initControls();window.addEventListener('resize',()=>{resizeCanvas(holder.clientWidth,holder.clientHeight)});let el=c.elt;el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);dragging=true;let q=position(e);px=q[0];py=q[1];inputs++;onDown(px,py)});el.addEventListener('pointermove',e=>{if(!dragging)return;let q=position(e);inputs++;onDrag(q[0],q[1],q[0]-px,q[1]-py);px=q[0];py=q[1];artAudio.fx(Math.floor(px/80),.45)});el.addEventListener('pointerup',e=>{dragging=false;onUp();updateStatus()});el.addEventListener('pointercancel',()=>dragging=false);button('reset',()=>{resets++;initialise();artAudio.reset()});updateStatus();}
function position(e){let r=document.getElementById('art').getBoundingClientRect();return[(e.clientX-r.left)/r.width*1000,(e.clientY-r.top)/r.height*760]}
function draw(){frames++;time=millis()/1000;push();scale(width/1000,height/760);render();pop()}
function onUp(){}
function updateStatus(){document.getElementById('status').textContent=statusText()}
window.artworkSnapshot=()=>({inputs,resets,frames,state:stateSnapshot(),bounded:bounded(),counts:counts(),audio:artAudio.snapshot()});

let yaw=-.3,pitch=.8,bandWidth=90,wave=.3,twists=1,split=false,open=0,openTo=0,glaze=0;
const palettes=[['#e27665','#e8ad5b','#e0d5bd','#6caaac','#a479a2'],['#5088a3','#73b8a5','#d6cb68','#ac7697','#edaa85'],['#78629f','#b87da4','#e5a275','#9db3c7','#608987']];
function initialise(){yaw=-.3;pitch=.8;bandWidth=90;wave=.3;twists=1;split=false;open=openTo=0;glaze=0;mode='orbit';document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.id==='orbit'));}
function initControls(){choose('orbit','orbit');choose('shape','shape');button('twist',()=>{twists=twists===5?1:twists+2;artAudio.setMood(twists)});button('split',()=>split=!split);button('unfold',()=>openTo=openTo?0:1);button('glaze',()=>{glaze=(glaze+1)%3;artAudio.o.scale=[[43,50,55,58,62,65,67],[45,52,57,60,64,67,69],[48,55,60,63,67,70,72]][glaze]})}
function onDown(x,y){}function onDrag(x,y,dx,dy){if(mode==='orbit'){yaw+=dx*.008;pitch=clamp(pitch+dy*.007,-1.5,1.5)}else{bandWidth=clamp(bandWidth+dx*.45,35,150);wave=clamp(wave+dy*.006,-1.1,1.1)}}
function surface(t,v){let a=t*TAU,phase=a*twists/2,b=bandWidth*v*(split?.86:1);let x=(220+b*Math.cos(phase))*Math.cos(a),z=(220+b*Math.cos(phase))*Math.sin(a),y=b*Math.sin(phase)+Math.sin(a*3)*wave*65;let straightX=(t-.5)*650,straightY=v*bandWidth*1.1+Math.sin(t*8)*wave*30;return[ler(x,straightX,open),ler(y,straightY,open),ler(z,0,open)]}
function proj(p){let x=p[0]*Math.cos(yaw)+p[2]*Math.sin(yaw),z=-p[0]*Math.sin(yaw)+p[2]*Math.cos(yaw),y=p[1]*Math.cos(pitch)-z*Math.sin(pitch),zz=p[1]*Math.sin(pitch)+z*Math.cos(pitch);return[500+x,365+y,zz]}
function render(){bg('#1c2535','#343440');open=ler(open,openTo,.025);drawingContext.fillStyle=grad(500,360,400,'#56637450','#1c253500');drawingContext.fillRect(0,0,1000,760);fill('#0e152650');noStroke();ellipse(500,627,640,66);fill('#263244');ellipse(500,626,600,32);noFill();stroke('#bcb4914a');strokeWeight(1);ellipse(500,622,580,43);let faces=[],N=144,M=15;for(let i=0;i<N;i++)for(let j=0;j<M;j++){let v0=-1+j*2/M,v1=-1+(j+1)*2/M;if(split&&(j===4||j===9))continue;let a=proj(surface(i/N,v0)),b=proj(surface((i+1)/N,v0)),c=proj(surface((i+1)/N,v1)),d=proj(surface(i/N,v1));let dep=(a[2]+b[2]+c[2]+d[2])/4,pal=palettes[glaze],ix=Math.floor(i/N*pal.length)%pal.length;let ct=pal[ix],bright=.67+(Math.sin(i/N*TAU*twists+time*.18)*.5+.5)*.38+(j/M)*.12;faces.push({p:[a,b,c,d],z:dep,c:shade(ct,bright),edge:j===0||j===M-1})}faces.sort((a,b)=>a.z-b.z);for(let f of faces){poly(f.p,f.c);stroke(f.c);strokeWeight(.65);beginShape();f.p.forEach(p=>vertex(p[0],p[1]));endShape(CLOSE);if(f.edge){stroke('#ffe8af66');strokeWeight(1.4);line(f.p[0][0],f.p[0][1],f.p[1][0],f.p[1][1])}}noStroke();fill('#d0bb95');textFont('Georgia');textSize(12);textAlign(LEFT);text('SINGLE SIDED / '+twists+' HALF TURNS',43,55);fill('#aab0bc');textSize(10);text(split?'three separated enamel bands':'one continuous enamel surface',43,77);stroke('#c7b49755');strokeWeight(1);line(40,694,235,694);noStroke();fill('#c0b5a5');textSize(11);text('Rotate / Sculpt / Unfold',43,718)}
function statusText(){return twists+' 个半扭 · '+(split?'三条分带':'完整带面')+' · '+(openTo?'展开中':'环形雕塑')+' · '+['珊瑚釉','孔雀釉','暮光釉'][glaze]}
function stateSnapshot(){return{yaw,pitch,bandWidth,wave,twists,split,open,glaze,mode}}function bounded(){return bandWidth>=35&&bandWidth<=150}function counts(){return{surfaceQuads:split?1872:2160,cap:2160}}
